env:
  name: ParamBipedalWalker

num_episodes: 10000
batch_size: 32

algo: PPO
model_params:
  hidden_sizes: [256, 256]
  init_log_std: 0.0
  learning_rate: 3e-4
  discr: False
  in_dim: 24
  out_dim: 4

